[workspace]
members = [
    "solana/privacy_wrapper",
    "core",
    "client/rust",
    "examples/rust",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Glitch Gang Collective <info@glitch.gang>"]
repository = "https://github.com/glitch-gang/project-89"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
solana-program = "1.16.0"
solana-client = "1.16.0"
solana-sdk = "1.16.0"
borsh = "0.10.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
anyhow = "1.0.71"
rand = "0.8.5"
chacha20poly1305 = "0.10.1"
sha3 = "0.10.8"
ring = "0.16.20"
base64 = "0.21.2"
async-trait = "0.1.68"
futures = "0.3.28"
log = "0.4.17"
env_logger = "0.10.0"
tokio = { version = "1.28.2", features = ["full"] }
reqwest = { version = "0.11.18", features = ["json"] }
metaplex-token-metadata = { version = "0.0.1", features = ["no-entrypoint"] }
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1.2", features = ["no-entrypoint"] }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3

[profile.dev]
opt-level = 0
debug = true
