[package]
name = "project-89-client"
version = "0.1.0"
edition = "2021"
description = "Client library for Project 89: Quantum Veil privacy system"
authors = ["Glitch Gang Collective <info@glitch.gang>"]
repository = "https://github.com/glitch-gang/project-89"
license = "MIT"
readme = "README.md"

[dependencies]
# Core dependencies
solana-client = { workspace = true }
solana-sdk = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
ring = { workspace = true }
base64 = { workspace = true }
chacha20poly1305 = { workspace = true }
sha3 = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

# Internal dependencies
core = { path = "../../core" }

[dev-dependencies]
env_logger = { workspace = true }
tokio-test = "0.4.2"
mockito = "1.0.0"
test-case = "3.1.0"

[lib]
name = "project_89"
path = "src/lib.rs"

[features]
default = ["solana"]
solana = []
ipfs = []
arweave = []
quantum = []
