[package]
name = "privacy-wrapper"
version = "0.1.0"
edition = "2021"
description = "Privacy wrapper for existing NFTs on Solana blockchain"
license = "MIT"
repository = "https://github.com/glitch-gang/project-89"
readme = "README.md"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
solana-program = "1.16.0"
borsh = "0.10.3"
thiserror = "1.0.40"
num-derive = "0.4.0"
num-traits = "0.2.15"
metaplex-token-metadata = { version = "0.0.1", features = ["no-entrypoint"] }
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1.2", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.16.0"
solana-sdk = "1.16.0"
tokio = { version = "1.28.2", features = ["macros"] }

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
